HT-18/searsapp/products/urls.py
from django.urls import path

from . import views

app_name = "products"

urlpatterns = [
    path("", views.MyProductsView.as_view(), name="my_products"),
    path("product/<int:pk>/", views.ProductView.as_view(), name="product_details"),
    path("product/add/", views.ProductCreateView.as_view(), name="add_product"),
]

HT-18/searsapp/searsapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("admin/", admin.site.urls), path("", include("products.urls"))]

HT-18/searsapp/products/models.py
from django.db import models


class Product(models.Model):
    site_id = models.CharField(max_length=50)
    name = models.TextField()
    link = models.CharField(max_length=200)
    brand = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    store = models.CharField(max_length=50)
    current_price = models.DecimalField(max_digits=10, decimal_places=2)
    old_price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()


class ScrapingTask(models.Model):
    product_ids = models.TextField()

HT-18/searsapp/products/forms.py
from django import forms

from .models import Product


class CreateProductForm(forms.ModelForm):
    ids = forms.CharField(
        widget=forms.Textarea(
            attrs={"placeholder": "Enter IDs separated by comma.", "class": "form-control"}
        )
    )

    class Meta:
        model = Product
        fields = ["ids"]

HT-18/searsapp/products/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import View, generic

from .forms import CreateProductForm
from .models import Product, ScrapingTask
from .services import is_valid_ids, save_scraped_products


class MyProductsView(generic.ListView):
    template_name = "products/my_products.html"
    context_object_name = "my_products"

    def get_queryset(self):
        return Product.objects.order_by("-pk")


class ProductView(generic.DetailView):
    model = Product
    template_name = "products/product_details.html"


class ProductCreateView(View):
    template_name = "products/add_products.html"
    form_class = CreateProductForm
    success_url = reverse_lazy("products:add_product")

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # Get ID from form
            form_ids = form.cleaned_data["ids"]

            # Check if valid form input
            if not is_valid_ids(ids=form_ids):
                messages.error(
                    self.request,
                    "Wrong input formatting. Enter IDs separated by comma. "
                    "Example: A098254049,A085642481",
                )
                return HttpResponseRedirect(reverse("products:add_product"))

            # Create scraping task with input ids
            task = ScrapingTask.objects.create(product_ids=form_ids)

            # Save all products from ids
            save_scraped_products(task_id=task.pk)
            return HttpResponseRedirect(self.success_url)
        return render(request, self.template_name, {"form": form})

HT-18/searsapp/products/templates/products/add_products.html
{% extends "products/layout.html" %}

{% block title %}Add Product(s){% endblock %}

{% block body %}

{% if messages %}
    {% for message in messages %}
    {{ message }}
    {% endfor %}
{% endif %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>

{% endblock %}

HT-18/searsapp/products/templates/products/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'products/style.css' %}">

        <!-- http://getbootstrap.com/docs/5.1/ -->
        <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" rel="stylesheet">
        <script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"></script>
        
        {% block head %}{% endblock %}

    </head>
    <body>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'products:my_products' %}">My products</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'products:add_product' %}">Add product</a>
            </li>

        </ul>
        <hr>

    {% block body %}
    {% endblock %}
        
        
    </body>
</html>

HT-18/searsapp/products/templates/products/my_products.html
{% extends "products/layout.html" %}

{% block title %}My Products{% endblock %}

{% block body %}
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        {% for product in my_products %}
            <tr>
                <td><a href="{% url 'products:product_details' product.id %}">{{ product.name }}</a></td>
                <td>{{ product.current_price }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

HT-18/searsapp/products/templates/products/product_details.html
{% extends "products/layout.html" %}

{% block title %}Product Details{% endblock %}

{% block body %}
<div>
    <h3>{{ product.name }}</h3>
    <p>Description: {{ product.description|safe }}</p>
    <p>Current Price: {{ product.current_price }}</p>
    <p>Old Price: {{ product.old_price }}</p>
    <p>Brand: {{ product.brand }}</p>
    <p>Store: {{ product.store }}</p>
    <p>Category: {{ product.category }}</p>
    <a href="{{ product.link }}">View Product</a>
</div>
{% endblock %}